webapp:
  build: .
  command: bundle exec unicorn -E production -c config/unicorn.rb
  volumes:
    - .:/myapp
  links:
    - db
    - redis
  env_file: .env
  environment:
    RACK_ENV: production
    RAILS_ENV: production
    VIRTUAL_HOST: rails-template.docker
  ports:
    - "8080:8080"
db:
  image: mongo:3.0
  command: mongod --smallfiles --quiet
proxy:
  image: jwilder/nginx-proxy:latest
  ports:
    - "80:80"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
redis:
  image: redis
worker:
  build: .
  command: bundle exec sidekiq -e production -c 5
  env_file: .env
  environment:
    RAILS_ENV: production
  links:
    - db
    - redis
